fixed prefix

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -19,13 +19,19 @@ runs:
   steps:
     - name: Check version input
       shell: bash
+      env:
+        INPUT_VERSION: ${{ inputs.version }}
       run: |
-        if [[ -n "${{ inputs.version }}" ]]; then
-          if [[ "${{ inputs.version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-            echo "Manually provided version: ${{ inputs.version }}"
-            echo "new_version=${{ inputs.version }}" >> "$GITHUB_ENV"
+        if [[ -n "$INPUT_VERSION" ]]; then
+          if [[ "$INPUT_VERSION" =~ ^v?[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            if [[ "${INPUT_VERSION:0:1}" == "v" ]]; then
+              echo "USE_V_PREFIX=false" >> "$GITHUB_ENV"
+            fi
+
+            echo "Manually provided version: $INPUT_VERSION"
+            echo "new_version=$INPUT_VERSION" >> "$GITHUB_ENV"
           else
-            echo "Invalid version format: ${{ inputs.version }}" >&2
+            echo "Invalid version format: $INPUT_VERSION" >&2
             exit 1
           fi
         fi
@@ -63,7 +69,6 @@ runs:
       shell: bash
       env:
         INCREMENT: ${{ inputs.increment }}
-        USE_V_PREFIX: ${{ inputs.use_v_prefix }}
       run: |
         if [[ "$INCREMENT" == "major" ]]; then
           new_version=${{ steps.semvers.outputs.major }}
@@ -73,19 +78,23 @@ runs:
           new_version=${{ steps.semvers.outputs.patch }}
         fi
 
+        echo "new_version=$new_version" >> "$GITHUB_ENV"
+
+    - name: Set output
+      id: set_version
+      shell: bash
+      env:
+        USE_V_PREFIX: ${{ inputs.use_v_prefix }}
+      run: |
+        new_version="${{ env.new_version }}"
+
         USE_V_PREFIX="${USE_V_PREFIX,,}"
         if [[ "$USE_V_PREFIX" == "true" ]]; then
           new_version="v$new_version"
         fi
 
         echo "New version: $new_version"
-        echo "new_version=$new_version" >> "$GITHUB_ENV"
-
-    - name: Set output
-      id: set_version
-      shell: bash
-      run: |
-        echo "new_version=${{ env.new_version }}" >> "$GITHUB_OUTPUT"
+        echo "new_version=$new_version" >> "$GITHUB_OUTPUT"
 
 outputs:
   new_version:
